apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: cloudverse
  labels:
    app: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge:       1
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: 914834315117.dkr.ecr.us-east-1.amazonaws.com/cloudverse/notification-service:v1
          ports:
            - containerPort: 4006
          resources:
            requests:
              cpu:    50m
              memory: 64Mi
            limits:
              cpu:    200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 4006
            initialDelaySeconds: 10
            periodSeconds:       20
            timeoutSeconds:      5
            failureThreshold:    3
          readinessProbe:
            httpGet:
              path: /health
              port: 4006
            initialDelaySeconds: 5
            periodSeconds:       10
            timeoutSeconds:      3
            failureThreshold:    3
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: cloudverse
spec:
  selector:
    app: notification-service
  ports:
    - port:       4006
      targetPort: 4006
  type: ClusterIP
